export LOCAL_INSTALL_PATH=${HOME}/.local
export LD_LIBRARY_PATH=${LOCAL_INSTALL_PATH}/lib:$LD_LIBRARY_PATH

# GDRCOPY
export GDRCOPY_HOME=${LOCAL_INSTALL_PATH}

# NVSHEM
export NVSHMEM_DIR=${LOCAL_INSTALL_PATH}/nvshmem-3.3.20
export PATH=${NVSHMEM_DIR}/bin:${PATH}
export CPATH=${NVSHMEM_DIR}/include:${CPATH}
export LIBRARY_PATH=${NVSHMEM_DIR}/lib:${LIBRARY_PATH}